# Default values for infranode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: opespe/infranode
  tag: 1.1.0
  pullPolicy: IfNotPresent

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

serviceType: ClusterIP

producer:
  name: defproducera
  privkey: 5JVy44L4vmeMdhXbSzfHFzFzEXL4ZLjvkcNfPkWL5Gvo8iQWusN

extraconfig: []

backup_recovery:
  enabled: false

snapshot_recovery:
  enabled: true
  fileURI: gs://opes-one-prod-eos-data/prod/snapshots/snap_2022-04-21-04-30.tar.gz

peerDiscovery:
  addresses:
    - "pub-infra-p2p.opesx.io:9876"

auth:
  enabled: false

  # Refer to --allowed-connection setting in https://developers.eos.io/eosio-nodeos/v1.5.0/docs/net_plugin
  type: any

  # Refer to --peer-private-key setting in https://developers.eos.io/eosio-nodeos/v1.5.0/docs/net_plugin
  # This is the key that the relay node will use to authenticate with other nodes
  # Configured in the format of '["<EOS Public Key>","<EOS Private Key>"]'

  # peerPrivateKey: '["EOS8D9tQMSbzX15HNRtz728hqP7PLVGMCtwW56jgqYdwZWRCpu3Fn","5HyJXxv8Q9JJWsde6N3MVBt24GgeJBnAY7oXgPjTd9RRxye7Jio"]'

  # Refer to --peer-key setting in https://developers.eos.io/eosio-nodeos/v1.5.0/docs/net_plugin
  # List of public keys for nodes that are allow to connect to this relay's P2P endpoint
  # Must be specified if type is set to specified
  peerKeys: []
    # - EOS653RjpmiXAu9KyHp1oEVm7YFZRqzPWkHJFsKYLyv2FPhpHTBrW

puzzleService:
  enabled: true
  puzzleServiceUrl: wss://puzzler.opesx.io:443
  disableCertValidation: false

httpListenAddress: 0.0.0.0
maxClients: 25
maxTransactionTime: 500000
abiSerializerMaxTimeMs: 990000

genesisJson:
  initial_timestamp: 2019-08-09T12:00:00.000
  initial_key: EOS5bU93vZJaxenqn8KAmuYgTfAydTYRrbwmchZ4FPJ5g23WyYkpb
  initial_configuration:
    max_block_net_usage: 1048576
    target_block_net_usage_pct: 1000
    max_transaction_net_usage: 786432
    base_per_transaction_net_usage: 12
    net_usage_leeway: 500
    context_free_discount_net_usage_num: 20
    context_free_discount_net_usage_den: 100
    max_block_cpu_usage: 200000
    target_block_cpu_usage_pct: 1000
    max_transaction_cpu_usage: 150000
    min_transaction_cpu_usage: 100
    max_transaction_lifetime: 3600
    deferred_trx_expiration_window: 600
    max_transaction_delay: 3888000
    max_inline_action_size: 4096
    max_inline_action_depth: 4
    max_authority_depth: 6

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  ## EOSIO data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  annotations: {}
  accessMode: ReadWriteOnce
  size: 20Gi
