---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "infranode.fullname" . }}-keys
  labels:
    app: {{ template "infranode.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  producer.privkey: {{ .Values.producer.privkey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "infranode.fullname" . }}
  labels:
    app: {{ template "infranode.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  producer.ini: |-
    plugin = eosio::chain_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::net_plugin
    plugin = eosio::http_plugin
    plugin = eosio::history_api_plugin
    blocks-dir = /eosio-data/blocks
    max-clients = {{ .Values.maxClients }}
    max-transaction-time = {{ .Values.maxTransactionTime }}
    abi-serializer-max-time-ms = {{ .Values.abiSerializerMaxTimeMs }}
    p2p-listen-endpoint = 0.0.0.0:9876
    http-server-address = {{ .Values.httpListenAddress }}:8888
    http-validate-host = false
{{- if .Values.auth.enabled }}
    allowed-connection = {{ .Values.auth.type }}
{{- if and (not (eq .Values.auth.type "Any")) (not (eq .Values.auth.type "None")) }}
{{- range .Values.auth.peerKeys }}
    peer-key = {{ . | quote }}
{{- end }}
{{- end }}
{{- if .Values.auth.peerPrivateKey }}
    peer-private-key = {{ .Values.auth.peerPrivateKey }}
{{- end }}
{{- end }}
    producer-name = {{ .Values.producer.name }}
{{- if .Values.puzzleService.enabled }}
    plugin = eosio::puzzle_plugin
    puzzle-server-url = {{ .Values.puzzleService.puzzleServiceUrl }}
{{- if .Values.puzzleService.disableCertValidation }}
    puzzle-server-cert-validate = false
{{- end }}
{{- end }}
{{- range .Values.peerDiscovery.addresses }}
    p2p-peer-address = {{ . }}
{{- end }}
