---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infranode.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "infranode.name" . }}
    helm.sh/chart: {{ include "infranode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: p2p
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "infranode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
