apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accessnode.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "accessnode.name" . }}
    helm.sh/chart: {{ include "accessnode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  micronaut-environments: {{ .Values.micronautEnvironments | quote }}
  jws-algorithm: ES256K
  deep-link-host-url: {{ .Values.deepLinkHostUrl }}
  name: {{ .Values.name }}
  display-name: {{ .Values.displayName }}
{{- if .Values.ingress.enabled }}
  url: http{{ if $.Values.ingress.tls }}s{{ end }}://{{ (index .Values.ingress.hosts 0).host }}
{{- else }}
  url: https://{{ include "accessnode.fullname" . }}
{{- end }}
  batchservice-url: {{ .Values.batchService.url }}
  batchservice-retry-delay: {{ .Values.batchService.retryDelay | quote }}
  batchservice-retry-attempts: {{ .Values.batchService.retryAttempts | quote }}
  batchservice-api-version: {{ .Values.batchService.apiVersion | quote }}
  batchservice-opesservice-keys: {{ .Values.batchService.opesServiceKeys | quote }}
