apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "accessnode.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "accessnode.name" . }}
    helm.sh/chart: {{ include "accessnode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  jwk: {{ .Values.jwk | quote }}
